<a href="https://colab.research.google.com/github/A01368506/Regresi-n-Logistica/blob/main/ACT7_REGRESI%C3%93N_LOGISTICA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Actividad 6 (Regresión No Lineal)**


---
#Paola Alessandra Ruiz Cruz A01368506

In [759]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.special as special
from scipy.optimize import curve_fit
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [760]:
df = pd.read_csv('/content/cuentas_credicel.csv', encoding='latin1')
df


<ipython-input-760-6fbb4148fae6>:1: DtypeWarning: Columns (30) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/cuentas_credicel.csv', encoding='latin1')


folio       tag  folio_solicitud           fecha     marca  \
0          3  HDNAWQ3A               30  12/11/21 19:00       ZTE   
1          4  M418YNR4               33  12/11/21 19:15  MOTOROLA   
2          5  SZ7V3NZT               37  13/11/21 14:13       ZTE   
3          6  9I08UIQZ               38  13/11/21 15:45       ZTE   
4          7  JMF4LKYU               44  13/11/21 16:10  MOTOROLA   
...      ...       ...              ...             ...       ...   
22730  22967  92KQVRIX            96502  18/04/23 18:45  Motorola   
22731  22968  NWB2EA8J            96479  18/04/23 18:46  Motorola   
22732  22969  VDTRJ2W6            96442  18/04/23 18:47   Samsung   
22733  22970  PETLF56C            96536  18/04/23 18:49   Samsung   
22734  22971  2CI4N2WS            96534  18/04/23 18:49   Samsung   

                             modelo plazo  precio  enganche  descuento  ...  \
0                Blade A3 2020 RO B   26S  1949.0     780.0        0.0  ...   
1      LTE XT2097-12 E7I POWER Azul   13S  2999.0    1050.0        0.0  ...   
2                BLADE A3 2020 Gris   13S  1959.0     490.0        0.0  ...   
3                BLADE A3 2020 Gris   13S  1959.0     490.0        0.0  ...   
4                             G10 B   39S  4299.0    1075.0        0.0  ...   
...                             ...   ...     ...       ...        ...  ...   
22730                      Moto E13   26S  3349.0     297.0        0.0  ...   
22731                     Moto E22i   26S  4100.0    1209.0        0.0  ...   
22732                           A13   26S  4849.0    1152.0        0.0  ...   
22733                        A53 5G   39S  9799.0    2799.0        0.0  ...   
22734                        A22 5G   26S  5399.0    1086.0        0.0  ...   

       porc_eng  limite_credito  semana_actual  cp_cliente edad_cliente  \
0         40.02            5000             26         NaN         23.0   
1         35.01            6000             13         NaN         60.0   
2         25.01               0             74         NaN         58.0   
3         25.01            7000             13         NaN         42.0   
4         25.01            7000             74         NaN         33.0   
...         ...             ...            ...         ...          ...   
22730      8.87           10000              0       97880         22.0   
22731     29.49            5000              0       37295         27.0   
22732     23.76            4750              0       20210         36.0   
22733     28.56            7000              0       78434         53.0   
22734     20.11            4750              0       43800         19.0   

                        cd_cliente  edo_cliente                     cd_venta  \
0                                0            0                    Tantoyuca   
1                          PUEBLA          PUE.   Heroica Puebla de Zaragoza   
2                        TANTOYUCA         VER.                            0   
3                      AMXTLAN PUE          NaN                     Zacatlan   
4                       TANTOYUCA          VER.                    Tantoyuca   
...                            ...          ...                          ...   
22730                    OXKUTZCAB          YUC                    Oxkutzcab   
22731                         LEON          GTO                         Leon   
22732               AGUASCALIENTES          AGS               Aguascalientes   
22733  SOLEDAD DE GRACIANO SANCHEZ          SLP  Soledad De Graciano Sanchez   
22734                     TIZAYUCA          HGO            San Jose Del Cabo   

                 edo_venta                curp  
0                 Veracruz  AEVM980413MVZNDR02  
1                   Puebla  ZALC610119MPLPRR07  
2                        0                   0  
3                   Puebla  SAMJ790115MPLNRS02  
4                 Veracruz  TEHF880707HVZRRR07  
...                    ...                 ...  
22730              Yucat

In [761]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22735 entries, 0 to 22734
Data columns (total 39 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   folio               22735 non-null  int64  
 1   tag                 22735 non-null  object 
 2   folio_solicitud     22735 non-null  int64  
 3   fecha               22735 non-null  object 
 4   marca               22735 non-null  object 
 5   modelo              22735 non-null  object 
 6   plazo               22735 non-null  object 
 7   precio              22735 non-null  float64
 8   enganche            22735 non-null  float64
 9   descuento           22735 non-null  float64
 10  semana              22735 non-null  int64  
 11  monto_financiado    22735 non-null  float64
 12  costo_total         22735 non-null  int64  
 13  monto_accesorios    22735 non-null  float64
 14  agente_venta        22735 non-null  object 
 15  dis_venta           22735 non-null  object 
 16  stat

In [762]:
df.isnull().sum()

folio                    0
tag                      0
folio_solicitud          0
fecha                    0
marca                    0
modelo                   0
plazo                    0
precio                   0
enganche                 0
descuento                0
semana                   0
monto_financiado         0
costo_total              0
monto_accesorios         0
agente_venta             0
dis_venta                0
status                   0
fraude                   0
empresa                 13
inversion                0
pagos_realizados         0
reautorizacion           0
fecha_ultimo_pago     3356
fecha_pago_proximo    3356
status_cuenta         3314
puntos                   0
riesgo                   0
score_buro               0
razones_buro          7340
porc_eng                 0
limite_credito           0
semana_actual            0
cp_cliente            7243
edad_cliente             9
cd_cliente               0
edo_cliente              8
cd_venta                 0
e

In [763]:
fila= df.iloc[[10184,10954]]
df1 = df.drop([10184,10954],axis=0)
fila

df1["limite_credito"]= pd.to_numeric(df1["limite_credito"],errors="coerce")

In [764]:
df2 = df1.drop(["razones_buro","agente_venta","cp_cliente","fecha_ultimo_pago","fecha_pago_proximo","fecha","edo_cliente","cd_venta","cd_cliente","curp","tag","folio","folio_solicitud"],axis=1)
df2 =df2.fillna(method="ffill")
df2 =df2.fillna(method="bfill")
df2

marca                        modelo plazo  precio  enganche  \
0           ZTE            Blade A3 2020 RO B   26S  1949.0     780.0   
1      MOTOROLA  LTE XT2097-12 E7I POWER Azul   13S  2999.0    1050.0   
2           ZTE            BLADE A3 2020 Gris   13S  1959.0     490.0   
3           ZTE            BLADE A3 2020 Gris   13S  1959.0     490.0   
4      MOTOROLA                         G10 B   39S  4299.0    1075.0   
...         ...                           ...   ...     ...       ...   
22730  Motorola                      Moto E13   26S  3349.0     297.0   
22731  Motorola                     Moto E22i   26S  4100.0    1209.0   
22732   Samsung                           A13   26S  4849.0    1152.0   
22733   Samsung                        A53 5G   39S  9799.0    2799.0   
22734   Samsung                        A22 5G   26S  5399.0    1086.0   

       descuento  semana  monto_financiado  costo_total  monto_accesorios  \
0            0.0      81            1169.0         2106               0.0   
1            0.0     225            1949.0         2925               0.0   
2            0.0     170            1469.0         2210               0.0   
3            0.0     170            1469.0         2210               0.0   
4            0.0     178            3224.0         6942               0.0   
...          ...     ...               ...          ...               ...   
22730        0.0     211            3052.0         5486               0.0   
22731        0.0     200            2891.0         5200               0.0   
22732        0.0     256            3697.0         6656               0.0   
22733        0.0     386            7000.0        15054               0.0   
22734        0.0     299            4313.0         7774               0.0   

       ... reautorizacion  status_cuenta  puntos riesgo  score_buro  porc_eng  \
0      ...              0      Cancelado       0   0.00           0     40.02   
1      ...              0      Cancelado       0   0.00           0     35.01   
2      ...              0      Cancelado       0   0.00           0     25.01   
3      ...              0      Cancelado       0   0.00           0     25.01   
4      ...              0           Mora       0   0.00           0     25.01   
...    ...            ...            ...     ...    ...         ...       ...   
22730  ...              0      Cancelado      10  27.40         469      8.87   
22731  ...              0      Cancelado       9  19.00         502     29.49   
22732  ...              0      Cancelado      11  26.65         459     23.76   
22733  ...              0      Cancelado      14 -17.35         699     28.56   
22734  ...              0      Cancelado      12  21.80           0     20.11   

       limite_credito semana_actual  edad_cliente            edo_venta  
0                5000            26          23.0             Veracruz  
1                6000            13          60.0               Puebla  
2                   0            74          58.0                    0  
3                7000            13          42.0               Puebla  
4                7000            74          33.0             Veracruz  
...               ...           ...           ...                  ...  
22730           10000             0          22.0              Yucatan  
22731            5000             0          27.0           Guanajuato  
22732            4750             0          36.0       Aguascalientes  
22733            7000             0          53.0      San Luis Potosi  
22734            4750             0          19.0  Baja California Sur  

[22733 rows x 26 columns]

In [765]:
df2.isnull().sum()

marca               0
modelo              0
plazo               0
precio              0
enganche            0
descuento           0
semana              0
monto_financiado    0
costo_total         0
monto_accesorios    0
dis_venta           0
status              0
fraude              0
empresa             0
inversion           0
pagos_realizados    0
reautorizacion      0
status_cuenta       0
puntos              0
riesgo              0
score_buro          0
porc_eng            0
limite_credito      0
semana_actual       0
edad_cliente        0
edo_venta           0
dtype: int64

In [766]:
y=df2
Limite_Superior = y.mean(numeric_only=True) + 3 * y.std(numeric_only=True)
Limite_Inferior = y.mean(numeric_only=True) - 3 * y.std(numeric_only=True)

print("Limite superior permitido", Limite_Superior)
print("Limite inferior permitido", Limite_Inferior)

Limite superior permitido precio               8081.660632
enganche             2356.485872
descuento             478.233409
semana                541.276328
monto_financiado     6366.446292
costo_total         12857.922009
monto_accesorios      191.269482
status                  2.611125
fraude                  0.864169
inversion               1.511659
pagos_realizados       39.306541
reautorizacion          0.578112
puntos                 48.355862
riesgo                 58.453828
score_buro           1142.044924
porc_eng               45.711381
limite_credito      12330.216100
semana_actual          64.382766
edad_cliente          422.330150
dtype: float64
Limite inferior permitido precio               -87.662243
enganche            -503.666794
descuento           -321.268116
semana               -65.794166
monto_financiado    -214.191184
costo_total        -1458.487179
monto_accesorios    -164.339577
status                -0.100414
fraude                -0.714519
inversion         

In [767]:
cuentas= df2[(y<=Limite_Superior)&(y>=Limite_Inferior)]
cuentas

<ipython-input-767-2f18aa389e49>:1: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version. Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  cuentas= df2[(y<=Limite_Superior)&(y>=Limite_Inferior)]


marca modelo plazo  precio  enganche  descuento  semana  \
0       NaN    NaN   NaN  1949.0     780.0        0.0    81.0   
1       NaN    NaN   NaN  2999.0    1050.0        0.0   225.0   
2       NaN    NaN   NaN  1959.0     490.0        0.0   170.0   
3       NaN    NaN   NaN  1959.0     490.0        0.0   170.0   
4       NaN    NaN   NaN  4299.0    1075.0        0.0   178.0   
...     ...    ...   ...     ...       ...        ...     ...   
22730   NaN    NaN   NaN  3349.0     297.0        0.0   211.0   
22731   NaN    NaN   NaN  4100.0    1209.0        0.0   200.0   
22732   NaN    NaN   NaN  4849.0    1152.0        0.0   256.0   
22733   NaN    NaN   NaN     NaN       NaN        0.0   386.0   
22734   NaN    NaN   NaN  5399.0    1086.0        0.0   299.0   

       monto_financiado  costo_total  monto_accesorios  ... reautorizacion  \
0                1169.0       2106.0               0.0  ...            0.0   
1                1949.0       2925.0               0.0  ...            0.0   
2                1469.0       2210.0               0.0  ...            0.0   
3                1469.0       2210.0               0.0  ...            0.0   
4                3224.0       6942.0               0.0  ...            0.0   
...                 ...          ...               ...  ...            ...   
22730            3052.0       5486.0               0.0  ...            0.0   
22731            2891.0       5200.0               0.0  ...            0.0   
22732            3697.0       6656.0               0.0  ...            0.0   
22733               NaN          NaN               0.0  ...            0.0   
22734            4313.0       7774.0               0.0  ...            0.0   

       status_cuenta  puntos riesgo  score_buro  porc_eng  limite_credito  \
0                NaN     0.0   0.00           0     40.02          5000.0   
1                NaN     0.0   0.00           0     35.01          6000.0   
2                NaN     0.0   0.00           0     25.01             0.0   
3                NaN     0.0   0.00           0     25.01          7000.0   
4                NaN     0.0   0.00           0     25.01          7000.0   
...              ...     ...    ...         ...       ...             ...   
22730            NaN    10.0  27.40         469      8.87         10000.0   
22731            NaN     9.0  19.00         502     29.49          5000.0   
22732            NaN    11.0  26.65         459     23.76          4750.0   
22733            NaN    14.0 -17.35         699     28.56          7000.0   
22734            NaN    12.0  21.80           0     20.11          4750.0   

      semana_actual  edad_cliente  edo_venta  
0              26.0          23.0        NaN  
1              13.0          60.0        NaN  
2               NaN          58.0        NaN  
3              13.0          42.0        NaN  
4               NaN          33.0        NaN  
...             ...           ...        ...  
22730           0.0          22.0        NaN  
22731           0.0          27.0        NaN  
22732           0.0          36.0        NaN  
22733           0.0          53.0        NaN  
22734           0.0          19.0        NaN  

[22733 rows x 26 columns]

In [768]:
cuentasl = df2.drop(["semana_actual","semana"],axis=1)
cuentasl = cuentasl.copy()
cuentasl = cuentasl.fillna(round(cuentasl.mean(),1))
cuentasl

<ipython-input-768-53821d16748d>:3: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  cuentasl = cuentasl.fillna(round(cuentasl.mean(),1))


marca                        modelo plazo  precio  enganche  \
0           ZTE            Blade A3 2020 RO B   26S  1949.0     780.0   
1      MOTOROLA  LTE XT2097-12 E7I POWER Azul   13S  2999.0    1050.0   
2           ZTE            BLADE A3 2020 Gris   13S  1959.0     490.0   
3           ZTE            BLADE A3 2020 Gris   13S  1959.0     490.0   
4      MOTOROLA                         G10 B   39S  4299.0    1075.0   
...         ...                           ...   ...     ...       ...   
22730  Motorola                      Moto E13   26S  3349.0     297.0   
22731  Motorola                     Moto E22i   26S  4100.0    1209.0   
22732   Samsung                           A13   26S  4849.0    1152.0   
22733   Samsung                        A53 5G   39S  9799.0    2799.0   
22734   Samsung                        A22 5G   26S  5399.0    1086.0   

       descuento  monto_financiado  costo_total  monto_accesorios dis_venta  \
0            0.0            1169.0         2106               0.0   mic0437   
1            0.0            1949.0         2925               0.0    mic015   
2            0.0            1469.0         2210               0.0   mic0437   
3            0.0            1469.0         2210               0.0   mic0748   
4            0.0            3224.0         6942               0.0   mic0437   
...          ...               ...          ...               ...       ...   
22730        0.0            3052.0         5486               0.0    svc044   
22731        0.0            2891.0         5200               0.0    PXC004   
22732        0.0            3697.0         6656               0.0    gph008   
22733        0.0            7000.0        15054               0.0    gph014   
22734        0.0            4313.0         7774               0.0    php005   

       ...  pagos_realizados  reautorizacion status_cuenta  puntos  riesgo  \
0      ...                 0               0     Cancelado       0    0.00   
1      ...                 0               0     Cancelado       0    0.00   
2      ...                 0               0     Cancelado       0    0.00   
3      ...                 0               0     Cancelado       0    0.00   
4      ...                 0               0          Mora       0    0.00   
...    ...               ...             ...           ...     ...     ...   
22730  ...                 0               0     Cancelado      10   27.40   
22731  ...                 0               0     Cancelado       9   19.00   
22732  ...                 0               0     Cancelado      11   26.65   
22733  ...                 0               0     Cancelado      14  -17.35   
22734  ...                 0               0     Cancelado      12   21.80   

       score_buro porc_eng  limite_credito  edad_cliente            edo_venta  
0               0    40.02            5000          23.0             Veracruz  
1               0    35.01            6000          60.0               Puebla  
2               0    25.01               0          58.0                    0  
3               0    25.01            7000          42.0               Puebla  
4               0    25.01            7000          33.0             Veracruz  
...           ...      ...             ...           ...                  ...  
22730         469     8.87           10000          22.0              Yucatan  
22731         502    29.49            5000          27.0           Guanajuato  
22732         459    23.76            4750          36.0       Aguascalientes  
22733         699    28.56            7000          53.0      San Luis Potosi  
22734           0    20.11            4750          19.0  Baja California Sur  

[22733 rows x 24 columns]

Correlacion 1

In [769]:
unico = np.unique(df2['status'])
unico

array([1, 2, 3, 4])

In [770]:
df2['status']= df2['status'].replace(["3", "4"], "2")

In [771]:
Vars_Indep= df2[['monto_financiado', 'costo_total', 'enganche']]
Var_Dep= df2['status']

In [772]:
X= Vars_Indep
y= Var_Dep

In [773]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [774]:
escalar = StandardScaler()

In [775]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [776]:
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [777]:
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [778]:
y_pred = algoritmo.predict(X_test)
y_pred

array([1, 1, 1, ..., 1, 1, 1])

In [779]:
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[5112   72    0]
 [1564   38    0]
 [  32    2    0]]


In [780]:
from sklearn.metrics import precision_score

precision1 = precision_score(y_test, y_pred, average="micro", pos_label="1")
print('Precisión del modelo:')
print(precision1)

Precisión del modelo:
0.7551319648093842


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1396: UserWarning: Note that pos_label (set to '1') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


In [781]:
from sklearn.metrics import accuracy_score

exactitud1 = accuracy_score(y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud1)

Exactitud del modelo:
0.7551319648093842


In [782]:
from sklearn.metrics import recall_score

sensibilidad1 = recall_score(y_test, y_pred, average="micro", pos_label="1")
print('Sensibilidad del modelo:')
print(sensibilidad1)

Sensibilidad del modelo:
0.7551319648093842


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1396: UserWarning: Note that pos_label (set to '1') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


In [783]:
from sklearn.metrics import f1_score
puntajef1 = f1_score(y_test, y_pred, average="micro", pos_label="1")
print('Puntaje F1 del modelo:')
print(puntajef1)

Puntaje F1 del modelo:
0.7551319648093842


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1396: UserWarning: Note that pos_label (set to '1') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


Correlacion 2

In [784]:
unico1 = np.unique(df2['fraude'])
unico1

array([0, 1])

In [785]:
Vars_Indep1= df2[['precio', 'costo_total', 'monto_financiado']]
Var_Dep1= df2['fraude']

In [786]:
X= Vars_Indep1
y= Var_Dep1

In [787]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(X, y, test_size=0.3, random_state =None)

In [788]:
 escalar1 = StandardScaler()

In [789]:
X_train1 = escalar1.fit_transform(X_train)
X_test1 = escalar1.transform(X_test)

In [790]:
from sklearn.linear_model import LogisticRegression
algoritmo1 = LogisticRegression()

In [791]:
algoritmo1.fit(X_train1, y_train1)

LogisticRegression()

In [792]:
y_pred1 = algoritmo1.predict(X_test)
y_pred1

array([0, 0, 0, ..., 0, 0, 0])

In [793]:
from sklearn.metrics import confusion_matrix
matriz1 = confusion_matrix(y_test1, y_pred1)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[5112   72    0]
 [1564   38    0]
 [  32    2    0]]


In [794]:
from sklearn.metrics import precision_score

precision2 = precision_score(y_test1, y_pred1, average="micro", pos_label="1")
print('Precisión del modelo:')
print(precision2)

Precisión del modelo:
0.9215542521994134


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1396: UserWarning: Note that pos_label (set to '1') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


In [795]:
from sklearn.metrics import accuracy_score

exactitud2 = accuracy_score(y_test1, y_pred1)
print('Exactitud del modelo:')
print(exactitud2)

Exactitud del modelo:
0.9215542521994134


In [796]:
from sklearn.metrics import recall_score

sensibilidad2 = recall_score(y_test, y_pred, average="macro", pos_label="1")
print('Sensibilidad del modelo:')
print(sensibilidad2)

Sensibilidad del modelo:
0.3366104868913858


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1396: UserWarning: Note that pos_label (set to '1') is ignored when average != 'binary' (got 'macro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


In [797]:
from sklearn.metrics import f1_score
puntajef12 = f1_score(y_test1, y_pred1, average="micro", pos_label="1")
print('Puntaje F1 del modelo:')
print(puntajef12)

Puntaje F1 del modelo:
0.9215542521994134


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1396: UserWarning: Note that pos_label (set to '1') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


Correlacion 3


In [798]:
unico = np.unique(df2['inversion'])
unico

array([0, 1])

In [799]:
Vars_Indep2= df2[['costo_total', 'descuento', 'monto_financiado']]
Var_Dep2= df2['inversion']

In [800]:
X= Vars_Indep2
y= Var_Dep2

In [801]:
X_train2, X_test2, y_train2, y_test2 = train_test_split(X, y, test_size=0.3, random_state =None)

In [802]:
escalar2 = StandardScaler()

In [803]:
X_train2 = escalar2.fit_transform(X_train2)
X_test2 = escalar2.transform(X_test2)

In [804]:
from sklearn.linear_model import LogisticRegression
algoritmo2 = LogisticRegression()

In [805]:
algoritmo2.fit(X_train2, y_train2)

LogisticRegression()

In [806]:
y_pred2 = algoritmo2.predict(X_test2)
y_pred2

array([0, 0, 0, ..., 0, 0, 0])

In [807]:
from sklearn.metrics import confusion_matrix
matriz2 = confusion_matrix(y_test2, y_pred2)
print('Matriz de Confusión:')
print(matriz2)

Matriz de Confusión:
[[5007  192]
 [1479  142]]


In [808]:
from sklearn.metrics import precision_score

precision3 = precision_score(y_test2, y_pred2, average="micro", pos_label="1")
print('Precisión del modelo:')
print(precision3)

Precisión del modelo:
0.7549853372434018


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1396: UserWarning: Note that pos_label (set to '1') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


In [809]:
from sklearn.metrics import accuracy_score

exactitud3 = accuracy_score(y_test2, y_pred2)
print('Exactitud del modelo:')
print(exactitud3)

Exactitud del modelo:
0.7549853372434018


In [810]:
from sklearn.metrics import recall_score

sensibilidad3 = recall_score(y_test2, y_pred2, average="micro", pos_label="1")
print('Sensibilidad del modelo:')
print(sensibilidad3)

Sensibilidad del modelo:
0.7549853372434018


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1396: UserWarning: Note that pos_label (set to '1') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


In [811]:
from sklearn.metrics import f1_score
puntajef13 = f1_score(y_test2, y_pred2, average="micro", pos_label="1")
print('Puntaje F1 del modelo:')
print(puntajef13)

Puntaje F1 del modelo:
0.7549853372434018


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1396: UserWarning: Note that pos_label (set to '1') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


Correlación 4

In [812]:
unico = np.unique(df2['reautorizacion'])
unico

array([0, 1])

In [813]:
Vars_Indep4= df2[['precio', 'enganche', 'costo_total']]
Var_Dep4= df2['reautorizacion']

In [814]:
X= Vars_Indep4
y= Var_Dep4

In [815]:
X_train4, X_test4, y_train4, y_test4 = train_test_split(X, y, test_size=0.3, random_state =None)

In [816]:
escalar4 = StandardScaler()

In [817]:
X_train4 = escalar4.fit_transform(X_train4)
X_test4 = escalar4.transform(X_test4)

In [818]:
from sklearn.linear_model import LogisticRegression
algoritmo4 = LogisticRegression()

In [819]:
algoritmo4.fit(X_train4, y_train4)

LogisticRegression()

In [820]:
y_pred4 = algoritmo4.predict(X_test4)
y_pred4

array([0, 0, 0, ..., 0, 0, 0])

In [821]:
from sklearn.metrics import confusion_matrix
matriz4 = confusion_matrix(y_test4, y_pred4)
print('Matriz de Confusión:')
print(matriz4)

Matriz de Confusión:
[[6601    0]
 [ 219    0]]


In [822]:
from sklearn.metrics import precision_score

precision4 = precision_score(y_test4, y_pred4, average="micro", pos_label="1")
print('Precisión del modelo:')
print(precision4)

Precisión del modelo:
0.9678885630498534


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1396: UserWarning: Note that pos_label (set to '1') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


In [823]:
from sklearn.metrics import accuracy_score

exactitud4 = accuracy_score(y_test4, y_pred4)
print('Exactitud del modelo:')
print(exactitud4)

Exactitud del modelo:
0.9678885630498534


In [824]:
from sklearn.metrics import recall_score

sensibilidad4 = recall_score(y_test4, y_pred4, average="micro", pos_label="1")
print('Sensibilidad del modelo:')
print(sensibilidad4)

Sensibilidad del modelo:
0.9678885630498534


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1396: UserWarning: Note that pos_label (set to '1') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


In [825]:
from sklearn.metrics import f1_score
puntajef14 = f1_score(y_test4, y_pred4, average="micro", pos_label="1")
print('Puntaje F1 del modelo:')
print(puntajef14)

Puntaje F1 del modelo:
0.9678885630498534


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1396: UserWarning: Note that pos_label (set to '1') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


Correlacion 5

In [826]:
unico = np.unique(df2['marca'])
unico

array(['ALCATEL', 'Alcatel', 'B2M', 'HISENSE', 'Hisense', 'Huawei',
       'INCO', 'KODAK', 'LANIX', 'LG', 'Lanix', 'MOTOROLA', 'Motorola',
       'NOKIA', 'NYX', 'Nokia', 'RT', 'SAMSUNG', 'SENWA', 'Samsung',
       'Senwa', 'TCL', 'TECHPAD', 'TECNO MOBILE', 'VIVO', 'Vivo', 'WIKO',
       'ZTE', 'alcatel'], dtype=object)

In [827]:
df2['marca']= df2['marca'].replace(["ALCATEL","Alcatel","NOKIA","NYX","Nokia","RT","alcatel","SENWA","WIKO","Senwa","TCL","Samsung","SAMSUNG","TECHPAD","TECNO MOBILE","Vivo","VIVO","Motorola","B2M","HISENSE","Huawei","INCO","KODAK","LANIX","MOTOROLA"], "otro")

In [828]:
Vars_Indep5= df2[['precio', 'descuento', 'enganche']]
Var_Dep5= df2['marca']

In [829]:
X= Vars_Indep5
y= Var_Dep5

In [830]:
X_train5, X_test5, y_train5, y_test5 = train_test_split(X, y, test_size=0.3, random_state =None)

In [831]:
escalar5 = StandardScaler()

In [832]:
X_train5 = escalar5.fit_transform(X_train5)
X_test5 = escalar5.transform(X_test5)

In [833]:
from sklearn.linear_model import LogisticRegression
algoritmo5 = LogisticRegression()

In [834]:
algoritmo5.fit(X_train5, y_train5)

LogisticRegression()

In [835]:
y_pred5 = algoritmo5.predict(X_test)
y_pred5

array(['otro', 'ZTE', 'otro', ..., 'otro', 'otro', 'otro'], dtype=object)

In [836]:
from sklearn.metrics import confusion_matrix
matriz5 = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz5)

Matriz de Confusión:
[[5112   72    0]
 [1564   38    0]
 [  32    2    0]]


In [837]:
from sklearn.metrics import precision_score

precision5 = precision_score(y_test5, y_pred5, average="micro", pos_label="ZTE")
print('Precisión del modelo:')
print(precision5)

Precisión del modelo:
0.8306451612903226


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1396: UserWarning: Note that pos_label (set to 'ZTE') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


In [838]:
from sklearn.metrics import accuracy_score

exactitud5 = accuracy_score(y_test5, y_pred5)
print('Exactitud del modelo:')
print(exactitud5)

Exactitud del modelo:
0.8306451612903226


In [839]:
from sklearn.metrics import recall_score

sensibilidad5 = recall_score(y_test5, y_pred5, average="micro", pos_label="ZTE")
print('Sensibilidad del modelo:')
print(sensibilidad5)

Sensibilidad del modelo:
0.8306451612903226


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1396: UserWarning: Note that pos_label (set to 'ZTE') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


In [840]:
from sklearn.metrics import f1_score
puntajef15 = f1_score(y_test5, y_pred5, average="micro", pos_label="ZTE")
print('Puntaje F1 del modelo:')
print(puntajef15)

Puntaje F1 del modelo:
0.8306451612903226


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1396: UserWarning: Note that pos_label (set to 'ZTE') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


Correlación 6

In [841]:
unico = np.unique(df2['status_cuenta'])
unico

array(['Atraso', 'Cancelado', 'Corriente', 'Fraude', 'Mora'], dtype=object)

In [842]:
df2['status_cuenta']= df2['status_cuenta'].replace(["Atraso", "Cancelado","Fraude","Mora"], "No al corriente")

In [843]:
Vars_Indep6= df2[['monto_financiado', 'costo_total', 'enganche']]
Var_Dep6= df2['status_cuenta']

In [844]:
X= Vars_Indep6
y= Var_Dep6

In [845]:
X_train6, X_test6, y_train6, y_test6 = train_test_split(X, y, test_size=0.3, random_state =None)

In [846]:
escalar6 = StandardScaler()

In [847]:
X_train6 = escalar6.fit_transform(X_train6)
X_test6 = escalar6.transform(X_test6)

In [848]:
from sklearn.linear_model import LogisticRegression
algoritmo6 = LogisticRegression()

In [849]:
algoritmo6.fit(X_train6, y_train6)

LogisticRegression()

In [850]:
y_pred6 = algoritmo6.predict(X_test6)
y_pred6

array(['Corriente', 'No al corriente', 'No al corriente', ...,
       'Corriente', 'No al corriente', 'Corriente'], dtype=object)

In [851]:
from sklearn.metrics import confusion_matrix
matriz6 = confusion_matrix(y_test6, y_pred6)
print('Matriz de Confusión:')
print(matriz6)

Matriz de Confusión:
[[ 911 2415]
 [ 822 2672]]


In [852]:
from sklearn.metrics import precision_score

precision6 = precision_score(y_test6, y_pred6, average="weighted", pos_label="corriente")
print('Precisión del modelo:')
print(precision6)

Precisión del modelo:
0.5254640986216733


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1396: UserWarning: Note that pos_label (set to 'corriente') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


In [853]:
from sklearn.metrics import accuracy_score

exactitud6 = accuracy_score(y_test6, y_pred6)
print('Exactitud del modelo:')
print(exactitud6)

Exactitud del modelo:
0.525366568914956


In [854]:
from sklearn.metrics import recall_score

sensibilidad6 = recall_score(y_test6, y_pred6, average="weighted", pos_label="corriente")
print('Sensibilidad del modelo:')
print(sensibilidad6)

Sensibilidad del modelo:
0.525366568914956


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1396: UserWarning: Note that pos_label (set to 'corriente') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


In [855]:
from sklearn.metrics import f1_score
puntajef16 = f1_score(y_test6, y_pred6, average="micro", pos_label="corriente")
print('Puntaje F1 del modelo:')
print(puntajef16)

Puntaje F1 del modelo:
0.525366568914956


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1396: UserWarning: Note that pos_label (set to 'corriente') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


Correlacion 7

In [856]:
unico = np.unique(df2['status'])
unico

array([1, 2, 3, 4])

In [857]:
df2['edo_venta']= df2['edo_venta'].replace(["3", "4"], "2")

In [858]:
Vars_Indep7= df2[['precio', 'descuento', 'edad_cliente']]
Var_Dep7= df2['status']

In [859]:
X= Vars_Indep7
y= Var_Dep7

In [860]:
X_train7, X_test7, y_train7, y_test7 = train_test_split(X, y, test_size=0.3, random_state =None)

In [861]:
escalar7 = StandardScaler()

In [862]:
X_train7 = escalar7.fit_transform(X_train7)
X_test7 = escalar7.transform(X_test7)

In [863]:
from sklearn.linear_model import LogisticRegression
algoritmo7 = LogisticRegression()

In [864]:
algoritmo7.fit(X_train7, y_train7)

LogisticRegression()

In [865]:
y_pred7 = algoritmo7.predict(X_test7)
y_pred7

array([1, 1, 1, ..., 1, 1, 1])

In [866]:
from sklearn.metrics import confusion_matrix
matriz7 = confusion_matrix(y_test7, y_pred7)
print('Matriz de Confusión:')
print(matriz7)

Matriz de Confusión:
[[5183    0    0    0]
 [1592    0    0    0]
 [  44    0    0    0]
 [   1    0    0    0]]


In [867]:
from sklearn.metrics import precision_score

precision7 = precision_score(y_test7, y_pred7, average="micro", pos_label="1")
print('Precisión del modelo:')
print(precision7)

Precisión del modelo:
0.7599706744868036


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1396: UserWarning: Note that pos_label (set to '1') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


In [868]:
from sklearn.metrics import accuracy_score

exactitud7 = accuracy_score(y_test7, y_pred7)
print('Exactitud del modelo:')
print(exactitud7)

Exactitud del modelo:
0.7599706744868036


In [869]:
from sklearn.metrics import recall_score

sensibilidad7 = recall_score(y_test7, y_pred7, average="weighted", pos_label="1")
print('Sensibilidad del modelo:')
print(sensibilidad7)

Sensibilidad del modelo:
0.7599706744868036


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1396: UserWarning: Note that pos_label (set to '1') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


In [870]:
from sklearn.metrics import f1_score
puntajef17 = f1_score(y_test7, y_pred7, average="micro", pos_label="1")
print('Puntaje F1 del modelo:')
print(puntajef17)

Puntaje F1 del modelo:
0.7599706744868036


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1396: UserWarning: Note that pos_label (set to '1') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


Correlacion 8

In [871]:
unico = np.unique(df2['inversion'])
unico

array([0, 1])

In [872]:
Vars_Indep8= df2[['precio', 'costo_total', 'limite_credito']]
Var_Dep8= df2['inversion']


In [873]:
X= Vars_Indep8
y= Var_Dep8

In [874]:
X_train8, X_test8, y_train8, y_test8 = train_test_split(X, y, test_size=0.3, random_state =None)

In [875]:
escalar8 = StandardScaler()

In [876]:
X_train8 = escalar8.fit_transform(X_train8)
X_test8 = escalar8.transform(X_test8)

In [877]:
from sklearn.linear_model import LogisticRegression
algoritmo8 = LogisticRegression()

In [878]:
algoritmo8.fit(X_train8, y_train8)

LogisticRegression()

In [879]:
y_pred8 = algoritmo.predict(X_test8)
y_pred8

array([1, 1, 1, ..., 2, 1, 1])

In [880]:
from sklearn.metrics import confusion_matrix
matriz8 = confusion_matrix(y_test8, y_pred8)
print('Matriz de Confusión:')
print(matriz8)

Matriz de Confusión:
[[   0 4752  480]
 [   0 1477  111]
 [   0    0    0]]


In [881]:
from sklearn.metrics import precision_score

precision8 = precision_score(y_test8, y_pred8, average="micro", pos_label="1")
print('Precisión del modelo:')
print(precision8)

Precisión del modelo:
0.21656891495601174


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1396: UserWarning: Note that pos_label (set to '1') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


In [882]:
from sklearn.metrics import accuracy_score

exactitud8 = accuracy_score(y_test8, y_pred8)
print('Exactitud del modelo:')
print(exactitud8)

Exactitud del modelo:
0.21656891495601174


In [883]:
from sklearn.metrics import recall_score

sensibilidad8 = recall_score(y_test8, y_pred8, average="weighted", pos_label="1")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.3447820999560429


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1396: UserWarning: Note that pos_label (set to '1') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [884]:
from sklearn.metrics import f1_score
puntajef18 = f1_score(y_test8, y_pred8, average="micro", pos_label="1")
print('Puntaje F1 del modelo:')
print(puntajef18)

Puntaje F1 del modelo:
0.21656891495601174


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1396: UserWarning: Note that pos_label (set to '1') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


Correlacion 9

In [885]:
unico = np.unique(df2['reautorizacion'])
unico

array([0, 1])

In [886]:
Vars_Indep9= df2[['monto_financiado', 'score_buro', 'porc_eng']]
Var_Dep9= df2['reautorizacion']


In [887]:
X= Vars_Indep9
y= Var_Dep9

In [888]:
X_train9, X_test9, y_train9, y_test9 = train_test_split(X, y, test_size=0.3, random_state =None)

In [889]:
escalar9 = StandardScaler()

In [890]:
X_train9 = escalar9.fit_transform(X_train9)
X_test9 = escalar9.transform(X_test9)

In [891]:
from sklearn.linear_model import LogisticRegression
algoritmo9 = LogisticRegression()

In [892]:
algoritmo9.fit(X_train9, y_train9)

LogisticRegression()

In [893]:
y_pred9 = algoritmo9.predict(X_test9)
y_pred9

array([0, 0, 0, ..., 0, 0, 0])

In [894]:
from sklearn.metrics import confusion_matrix
matriz9 = confusion_matrix(y_test9, y_pred9)
print('Matriz de Confusión:')
print(matriz9)

Matriz de Confusión:
[[6572    0]
 [ 248    0]]


In [895]:
from sklearn.metrics import precision_score

precision9 = precision_score(y_test9, y_pred9, average="micro", pos_label="1")
print('Precisión del modelo:')
print(precision9)

Precisión del modelo:
0.9636363636363636


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1396: UserWarning: Note that pos_label (set to '1') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


In [896]:
from sklearn.metrics import accuracy_score

exactitud9 = accuracy_score(y_test9, y_pred9)
print('Exactitud del modelo:')
print(exactitud9)

Exactitud del modelo:
0.9636363636363636


In [897]:
from sklearn.metrics import recall_score

sensibilidad9 = recall_score(y_test9, y_pred9, average="micro", pos_label="1")
print('Sensibilidad del modelo:')
print(sensibilidad9)

Sensibilidad del modelo:
0.9636363636363636


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1396: UserWarning: Note that pos_label (set to '1') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


In [898]:
from sklearn.metrics import f1_score
puntajef19 = f1_score(y_test9, y_pred9, average="micro", pos_label="1")
print('Puntaje F1 del modelo:')
print(puntajef19)

Puntaje F1 del modelo:
0.9636363636363636


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1396: UserWarning: Note that pos_label (set to '1') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


Correlacion 10

In [899]:
unico = np.unique(df2['fraude'])
unico

array([0, 1])

In [900]:
Vars_Indep10= df2[['edad_cliente', 'precio', 'enganche']]
Var_Dep10= df2['fraude']


In [901]:
X= Vars_Indep10
y= Var_Dep10

In [902]:
X_train10, X_test10, y_train10, y_test10 = train_test_split(X, y, test_size=0.3, random_state =None)

In [903]:
escalar10 = StandardScaler()

In [904]:
X_train10 = escalar10.fit_transform(X_train10)
X_test10 = escalar10.transform(X_test10)

In [905]:
from sklearn.linear_model import LogisticRegression
algoritmo10 = LogisticRegression()

In [906]:
algoritmo10.fit(X_train10, y_train10)

LogisticRegression()

In [907]:
y_pred10 = algoritmo10.predict(X_test10)
y_pred10

array([0, 0, 0, ..., 0, 0, 0])

In [908]:
from sklearn.metrics import confusion_matrix
matriz10 = confusion_matrix(y_test10, y_pred10)
print('Matriz de Confusión:')
print(matriz10)

Matriz de Confusión:
[[6323    0]
 [ 497    0]]


In [909]:
from sklearn.metrics import precision_score

precision10 = precision_score(y_test10, y_pred10, average="micro", pos_label="1")
print('Precisión del modelo:')
print(precision10)

Precisión del modelo:
0.9271260997067449


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1396: UserWarning: Note that pos_label (set to '1') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


In [910]:
from sklearn.metrics import accuracy_score

exactitud10 = accuracy_score(y_test10, y_pred10)
print('Exactitud del modelo:')
print(exactitud10)

Exactitud del modelo:
0.9271260997067449


In [911]:
from sklearn.metrics import recall_score

sensibilidad10 = recall_score(y_test10, y_pred10, average="micro", pos_label="1")
print('Sensibilidad del modelo:')
print(sensibilidad10)

Sensibilidad del modelo:
0.9271260997067449


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1396: UserWarning: Note that pos_label (set to '1') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


In [912]:
from sklearn.metrics import f1_score
puntajef110 = f1_score(y_test10, y_pred10, average="micro", pos_label="1")
print('Puntaje F1 del modelo:')
print(puntajef110)

Puntaje F1 del modelo:
0.9271260997067449


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1396: UserWarning: Note that pos_label (set to '1') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


Tabla de coeficientes de precisión, exactitud y sensibilidad

In [916]:
precision_list = [precision10, precision2, precision3, precision4, precision5, precision6, precision7, precision8, precision9, precision10]
exactitud_list = [exactitud1, exactitud2, exactitud3, exactitud4, exactitud5, exactitud6, exactitud7, exactitud8, exactitud9, exactitud10]
sensibilidad_list = [sensibilidad1, sensibilidad2, sensibilidad3, sensibilidad4, sensibilidad5, sensibilidad6, sensibilidad7, sensibilidad8, sensibilidad9, sensibilidad10]
puntajef1_list = [puntajef1, puntajef12, puntajef13, puntajef14, puntajef15, puntajef16, puntajef17, puntajef18, puntajef19, puntajef110]

In [918]:
df3 = pd.DataFrame({'Precision': precision_list, 'Exactitud': exactitud_list, 'Sensibilidad': sensibilidad_list, 'Puntaje F1': puntajef1_list})
df3

Precision  Exactitud  Sensibilidad  Puntaje F1
0   0.927126   0.755132      0.755132    0.755132
1   0.921554   0.921554      0.336610    0.921554
2   0.754985   0.754985      0.754985    0.754985
3   0.967889   0.967889      0.967889    0.967889
4   0.830645   0.830645      0.830645    0.830645
5   0.525464   0.525367      0.525367    0.525367
6   0.759971   0.759971      0.759971    0.759971
7   0.216569   0.216569      0.216569    0.216569
8   0.963636   0.963636      0.963636    0.963636
9   0.927126   0.927126      0.927126    0.927126